const js = require("@eslint/js");
const prettierConfig = require("eslint-config-prettier");
const prettierPlugin = require("eslint-plugin-prettier");
const promisePlugin = require("eslint-plugin-promise");
const reactPlugin = require("eslint-plugin-react");
const simpleImportSortPlugin = require("eslint-plugin-simple-import-sort");
const tsPlugin = require("@typescript-eslint/eslint-plugin");
const tsParser = require("@typescript-eslint/parser");

module.exports = [
  {
    ignores: ["**/*.js", "coverage/**", "dist/**", "node_modules/**"],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: false,
    },
  },
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      globals: {
        __dirname: "readonly",
        analytics: "readonly",
        console: "readonly",
        Gtag: "readonly",
        gtag: "readonly",
        module: "readonly",
        process: "readonly",
        Promise: "readonly",
        require: "readonly",
        window: "readonly",
      },
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
          modules: true,
        },
        ecmaVersion: 6,
        sourceType: "module",
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      prettier: prettierPlugin,
      promise: promisePlugin,
      react: reactPlugin,
      "simple-import-sort": simpleImportSortPlugin,
    },
    settings: {
      "import/parsers": {
        "@typescript-eslint/parser": [".ts", ".tsx"],
      },
      "import/resolver": {
        alias: {
          extensions: [".json", ".ts", ".tsx"],
          map: [["~", "./src"]],
        },
        typescript: {},
      },
      react: { version: "detect" },
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      ...reactPlugin.configs.recommended.rules,
      ...prettierConfig.rules,
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/no-empty-function": "warn",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-inferrable-types": "off",
      "@typescript-eslint/no-unsafe-function-type": "off",
      "@typescript-eslint/no-unused-vars": "warn",
      "arrow-spacing": "error",
      "consistent-this": "off",
      curly: ["error", "all"],
      "dot-notation": "error",
      eqeqeq: "error",
      "func-name-matching": "error",
      "lines-between-class-members": [
        "error",
        "always",
        { exceptAfterSingleLine: true },
      ],
      "max-len": [
        "error",
        {
          code: 80,
          ignoreComments: true,
          ignorePattern: "^import\\s.+\\sfrom\\s.+;$",
          ignoreRegExpLiterals: true,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
        },
      ],
      "new-cap": "off",
      "no-alert": "warn",
      "no-constant-binary-expression": "off",
      "no-duplicate-imports": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-empty-function": "off",
      "no-empty-pattern": "warn",
      "no-eq-null": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-floating-decimal": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-iterator": "error",
      "no-lone-blocks": "warn",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-new-wrappers": "error",
      "no-redeclare": "off",
      "no-proto": "error",
      "no-restricted-properties": "warn",
      "no-return-assign": "error",
      "no-return-await": "off",
      "no-script-url": "error",
      "no-self-compare": "warn",
      "no-sequences": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-trailing-spaces": "error",
      "no-unneeded-ternary": "error",
      "no-unused-expressions": "warn",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-undef": "off",
      "no-var": "error",
      "no-void": "error",
      "no-warning-comments": ["off", { location: "anywhere" }],
      "no-whitespace-before-property": "error",
      "no-with": "error",
      "object-shorthand": "error",
      "one-var": ["error", "never"],
      "operator-assignment": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-destructuring": ["error", { array: false, object: true }],
      "prefer-numeric-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "prettier/prettier": "error",
      radix: ["error", "as-needed"],
      "react/display-name": "off",
      "react/jsx-filename-extension": [
        "error",
        {
          extensions: ["tsx"],
        },
      ],
      "react/no-unescaped-entities": "off",
      "react/prop-types": "off",
      "require-atomic-updates": "error",
      "require-await": "warn",
      "simple-import-sort/exports": "error",
      "simple-import-sort/imports": "error",
      yoda: "error",
    },
  },
];
