name: Checks

on: [push]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Checks
        run: yarn lint && yarn type-check
